// This file is auto-generated by scripts/generate-repo-stats.mjs
// Do not edit manually.

export interface GeneratedRepoCommitStats {
  sha: string;
  message: string;
  date: string;
  additions: number;
  deletions: number;
  changedFiles: number;
}

export interface GeneratedRepoStats {
  name: string;
  htmlUrl: string;
  description: string | null;
  defaultBranch: string;
  updatedAt: string | null;
  primaryLanguage: string | null;
  languages: string[];
  recentCommits: GeneratedRepoCommitStats[];
}

export const generatedRepoStats: GeneratedRepoStats[] = [
  {
    "name": "baerepo",
    "htmlUrl": "https://github.com/baej12/baerepo",
    "description": "This is the repository that hosts my website! ",
    "defaultBranch": "master",
    "updatedAt": "2026-05-26T02:34:18Z",
    "primaryLanguage": "TypeScript",
    "languages": [
      "TypeScript",
      "CSS",
      "JavaScript",
      "HTML"
    ],
    "recentCommits": [
      {
        "sha": "90d9f58",
        "message": "Merge pull request #83 from baej12/codex-fix-mobile-theme-color",
        "date": "2026-05-26",
        "additions": 23,
        "deletions": 3,
        "changedFiles": 4
      },
      {
        "sha": "bfdb9f9",
        "message": "Captcha modal fix 2",
        "date": "2026-05-26",
        "additions": 14,
        "deletions": 2,
        "changedFiles": 3
      },
      {
        "sha": "5190e95",
        "message": "Captcha fix",
        "date": "2026-05-26",
        "additions": 5,
        "deletions": 0,
        "changedFiles": 1
      }
    ]
  },
  {
    "name": "budget_it",
    "htmlUrl": "https://github.com/baej12/budget_it",
    "description": null,
    "defaultBranch": "main",
    "updatedAt": "2026-02-28T21:06:36Z",
    "primaryLanguage": "JavaScript",
    "languages": [
      "JavaScript",
      "CSS",
      "HTML"
    ],
    "recentCommits": [
      {
        "sha": "2c123ce",
        "message": "Add comprehensive technical documentation",
        "date": "2026-01-06",
        "additions": 776,
        "deletions": 0,
        "changedFiles": 1
      },
      {
        "sha": "fd4fe3c",
        "message": "Bundle react code",
        "date": "2026-01-06",
        "additions": 41,
        "deletions": 5,
        "changedFiles": 4
      },
      {
        "sha": "b17599a",
        "message": "Add comprehensive user and developer guide",
        "date": "2026-01-06",
        "additions": 131,
        "deletions": 0,
        "changedFiles": 1
      }
    ]
  },
  {
    "name": "leetcode",
    "htmlUrl": "https://github.com/baej12/leetcode",
    "description": "A repository containing all of my LeetCode solutions",
    "defaultBranch": "main",
    "updatedAt": "2026-02-28T20:46:42Z",
    "primaryLanguage": "C++",
    "languages": [
      "C++",
      "Python",
      "Shell",
      "PowerShell"
    ],
    "recentCommits": [
      {
        "sha": "b31b576",
        "message": "Merge branch 'main' of https://github.com/baej12/leetcode",
        "date": "2026-02-28",
        "additions": 829,
        "deletions": 0,
        "changedFiles": 7
      },
      {
        "sha": "b41d54a",
        "message": "Update gitignore. Solved 1800",
        "date": "2026-02-28",
        "additions": 109,
        "deletions": 0,
        "changedFiles": 2
      },
      {
        "sha": "c29290c",
        "message": "dq",
        "date": "2026-02-28",
        "additions": 125,
        "deletions": 0,
        "changedFiles": 1
      }
    ]
  },
  {
    "name": "baej12",
    "htmlUrl": "https://github.com/baej12/baej12",
    "description": "Config files for my GitHub profile.",
    "defaultBranch": "main",
    "updatedAt": "2025-12-18T22:32:45Z",
    "primaryLanguage": null,
    "languages": [],
    "recentCommits": [
      {
        "sha": "5967249",
        "message": "Updating again",
        "date": "2025-12-18",
        "additions": 68,
        "deletions": 45,
        "changedFiles": 1
      },
      {
        "sha": "e6b2267",
        "message": "Update README.me",
        "date": "2025-12-18",
        "additions": 55,
        "deletions": 100,
        "changedFiles": 1
      },
      {
        "sha": "60e1116",
        "message": "Remove some analytic links",
        "date": "2025-12-01",
        "additions": 2,
        "deletions": 3,
        "changedFiles": 1
      }
    ]
  },
  {
    "name": "play-dl",
    "htmlUrl": "https://github.com/baej12/play-dl",
    "description": "Mainly used for Discord js Bots to play music.",
    "defaultBranch": "main",
    "updatedAt": "2025-10-05T00:06:26Z",
    "primaryLanguage": "TypeScript",
    "languages": [
      "TypeScript"
    ],
    "recentCommits": [
      {
        "sha": "c4d4e0a",
        "message": "Config changes to allow for slightly easier debugging",
        "date": "2025-10-05",
        "additions": 5,
        "deletions": 1,
        "changedFiles": 1
      },
      {
        "sha": "6a8569f",
        "message": "Fixed find chapter error, soundcloud 403 and watch playlists",
        "date": "2023-09-24",
        "additions": 25,
        "deletions": 13,
        "changedFiles": 5
      },
      {
        "sha": "76c2373",
        "message": "Merge pull request #354 from karyeet/album-isrc-sto-patch",
        "date": "2023-07-12",
        "additions": 1,
        "deletions": 1,
        "changedFiles": 1
      }
    ]
  },
  {
    "name": "loancalculator",
    "htmlUrl": "https://github.com/baej12/loancalculator",
    "description": "Built a responsive loan calculator using React and TypeScript for quick financial insights. Enter loan amount, interest, and tenure to instantly compute monthly payments and total repayment, facilitating informed borrowing decisions.",
    "defaultBranch": "master",
    "updatedAt": "2024-02-24T07:44:50Z",
    "primaryLanguage": "TypeScript",
    "languages": [
      "TypeScript",
      "CSS",
      "HTML"
    ],
    "recentCommits": [
      {
        "sha": "9859094",
        "message": "init",
        "date": "2024-02-24",
        "additions": 31821,
        "deletions": 0,
        "changedFiles": 68
      }
    ]
  },
  {
    "name": "jpacman",
    "htmlUrl": "https://github.com/baej12/jpacman",
    "description": "Pacman-inspired game, for teaching reengineering purposes. (>= v9.0.0)",
    "defaultBranch": "master",
    "updatedAt": "2022-09-12T21:17:54Z",
    "primaryLanguage": null,
    "languages": [
      "Java",
      "Python"
    ],
    "recentCommits": [
      {
        "sha": "c0509b0",
        "message": "Update README.md",
        "date": "2022-09-12",
        "additions": 1,
        "deletions": 1,
        "changedFiles": 1
      },
      {
        "sha": "0c10fb2",
        "message": "New version of SonarQube on gradle.build",
        "date": "2021-02-19",
        "additions": 1,
        "deletions": 1,
        "changedFiles": 1
      },
      {
        "sha": "e951038",
        "message": "Clone detection tool",
        "date": "2021-02-10",
        "additions": 0,
        "deletions": 0,
        "changedFiles": 1
      }
    ]
  }
];

export default generatedRepoStats;
